default_context:
  project_name: 'fastapi-crud'
  project_slug: 'fastcrud'
  domain_main: 'fastcrud.com'
  domain_staging: 'stag.fastcrud.com'
  docker_swarm_stack_name_main: 'fastcrud-com'
  docker_swarm_stack_name_staging: 'stag-fastcrud-com'
  secret_key: 'c5d9e4eb3860d65dd5613cef2695b0ac04cb740d9e55d470edc3ad2349135f46'
  first_superuser: 'admin@fastcrud.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastcrud.com", "https://stag.fastcrud.com", "https://fastcrud.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastcrud.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@fastcrud.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'fastcrud.com'
  traefik_constraint_tag_staging: 'stag.fastcrud.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
